### ISSUE TITLE
Space Travelers - React Group Project

### ISSUE THREAD

**Issue by fbclh** [fbclh/space-travelers#25]
This is the Kanban board setup for our group project of two persons:
https://github.com/fbclh/space-travelers/projects/4
https://github.com/fbclh/space-travelers

**Comment by Wes-Isaac** [comment]
Hi, team (@fbclh & @sediqullahbadakhsh), 

Your project is complete!  There is nothing else to say other than... it's time to work on the project :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
